name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win32
          - os: macos-latest
            platform: darwin
          - os: ubuntu-latest
            platform: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd EveAssistant
          npm ci

      - name: Verify Electron Forge configuration
        run: |
          cd EveAssistant
          npm run make --dry-run || echo "Dry run failed, proceeding anyway"

      - name: Build and publish to GitHub Releases
        run: |
          cd EveAssistant
          echo "Current directory: $(pwd)"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          ls -la
          echo "Running npm run publish..."
          npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-forge:*

      - name: Build artifacts only (fallback)
        if: failure()
        run: |
          cd EveAssistant
          echo "Publish failed, trying make only..."
          npm run make
        continue-on-error: true

      - name: Upload build artifacts (fallback)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.platform }}
          path: |
            EveAssistant/out/make/**/*
            !EveAssistant/out/make/**/*.map
        continue-on-error: true 