name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    # Set default working directory
    defaults:
      run:
        working-directory: EveAssistant
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            platform: win32
          - os: macos-latest
            platform: darwin
          - os: ubuntu-latest
            platform: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: EveAssistant/package-lock.json

      - name: Install system dependencies (Linux)
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm2-dev libxcomposite-dev libxdamage-dev libxrandr-dev libgbm-dev libxss-dev libasound2-dev
          sudo apt-get install -y build-essential

      - name: Install system dependencies (macOS)
        if: matrix.platform == 'darwin'
        run: |
          # Ensure Python3 is available
          which python3 || echo "Python3 not found"

      - name: Install dependencies
        run: npm ci

      - name: Fix webpack-asset-relocator-loader compatibility
        run: |
          npm uninstall @vercel/webpack-asset-relocator-loader
          npm install @vercel/webpack-asset-relocator-loader@1.7.3

      - name: Build and publish (create draft release)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
        continue-on-error: true

      - name: Build artifacts only (fallback)
        if: failure()
        run: |
          echo "Publish failed, trying make only..."
          npm run make

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-installers
          path: EveAssistant/out/make/

      - name: List build outputs
        if: always()
        run: |
          echo "Contents of out directory:"
          ls -la out/ || echo "out directory not found"
          echo "Contents of out/make directory:"
          ls -la out/make/ || echo "out/make directory not found" 